name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate HTML
        run: |
          sudo apt-get update
          sudo apt-get install -y tidy
          tidy -e index.html || true
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Check for broken links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose .

  security:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Secret Scan
        uses: trufflesecurity/trufflehog@v3.63.3
        with:
          path: .
          base: main

  static-analysis:
    runs-on: ubuntu-latest
    needs: security
    steps:
      - uses: actions/checkout@v4
      - name: Lint CSS
        run: |
          npm install -g stylelint stylelint-config-standard
          npx stylelint "**/*.css" || true
      - name: Lint JavaScript
        run: |
          sudo apt-get install -y nodejs npm
          npm install -g jshint
          jshint **/*.js || true
  deploy:
    runs-on: ubuntu-latest
    needs: static-analysis
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .