name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate HTML
        run: |
          sudo apt-get update
          sudo apt-get install -y tidy
          tidy -e index.html || true
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Check for broken links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose .

  security:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Secret Scan
        uses: trufflesecurity/trufflehog@v3.63.3
        with:
          path: .
          base: main

  static-analysis:
    runs-on: ubuntu-latest
    needs: security
    steps:
      - uses: actions/checkout@v4
      - name: Lint CSS
        run: |
          npm install -g stylelint stylelint-config-standard
          npx stylelint "**/*.css" || true
      - name: Lint JavaScript
        run: |
          sudo apt-get install -y nodejs npm
          npm install -g jshint
          jshint **/*.js || true
      - name: Create reports directory
        run: |
          mkdir -p reports
          echo "Build completed successfully" > reports/build-report.txt
          echo "CSS and JS linting completed" > reports/lint-report.txt
      - name: Upload reports artifact
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
  deploy:
    runs-on: ubuntu-latest
    needs: static-analysis
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
